### ISSUE TITLE
IdsDataGrid: New M3 Example to show m3 features

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1019]
**Task**

Make a new m3 example that shows the things m3 uses for performance testing and finding the best ways.. Call it m3-features.html maybe?

**Features to include:**

- [x] Virtual Scroll
- [x] Tree (needs #1018 )
- [ ] Editor (needs #991 )
- [x] 10-20 columns
- [x] 500-1000 rows
- [x] Filtering with no filter icons
- [x] Conditional Styles
	- [x] Can be Any color including RGB
	- [x] Individual Per Cell
	- [x] Optional Icon (needs #990)
	- [x] Hyperlink instead text for content
	- [x] Text font styles
	- [x] Style the row color
	- [x] Every Cell Can be different
	
**Sample** (but just the grid part)

![image](https://user-images.githubusercontent.com/814283/204568548-a6cb5804-396d-48e4-a27f-752756d03ad4.png)

**Comment by janahintal** [comment]
QA Passed. Verified working in https://main.wc.design.infor.com/ids-data-grid/m3-features.html
![image](https://user-images.githubusercontent.com/45757016/211313044-5c0d27ac-79e6-42fa-9cbb-71cd795047a4.png)
