### ISSUE TITLE
InforOS: Adoption Epic 

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1286]
**Describe the bug**
Tasks needed for Infor OS Adoption

- [ ] New card features https://main-enterprise.demo.design.infor.com/components/cards/example-workspace-widgets.html
- [ ] Widget Component Vs Card Component
- [x] https://github.com/infor-design/enterprise/issues/7481
- [x] https://github.com/infor-design/enterprise/issues/7505
- [x] https://github.com/infor-design/enterprise/issues/7506
- [x] https://github.com/infor-design/enterprise/issues/7507
- [ ] New Splitter https://github.com/infor-design/enterprise/issues/7542
