### ISSUE TITLE
Misc: Find performance improvements

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#140]
**Describe the bug**
Look for web component improvements and make some tests.

**Tasks**

- [x] Document the tooltip perf test once merged
- [x] Add a datagrid perf test
- [x] Change from Constructed style sheets to links and test
- [x] Try adding https://developer.mozilla.org/en-US/docs/Web/CSS/contain https://developers.google.com/web/fundamentals/web-components/shadowdom#containment and testing as in

```
:host(ids-tooltip) {
  contain: content;
} 
```
- [x] See warnings on animation frame on http://localhost:4300/ids-list-view
- [x] Test load in fire fox as well

**Expected behavior**
Faster rendering

**Additional context**
Team Call...
See: https://blog.webpagetest.org/posts/benchmarking-javascript-memory-usage/
