### ISSUE TITLE
IdsModuleNav: Remaining Features/Issues

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#1417]
**Original Issue: #1226**
**PR: #1416**

**Major:**

- [x] Enhance IdsIcon to support Module Nav app icons, or create example using custom icon system to implement these icons
- [x] Implement tooltip support in "collapsed" display mode
- [x] Implement empty state when no filter results are available
- [x] Add IdsModuleNavItem styles to make text appear beneath ellipsis when cut off by overflow
- [x] Dark/Contrast modes
- [x] Complete Design Q/A from last round of EP module nav ([Figma doc](https://www.figma.com/file/bL4EBYtWjgfBsvTVI9seXU/branch/eHul2nKNMdypFLSb55ZwR1/Module-Nav-%7C-Application-Menu?type=design&node-id=5833-86117&mode=design&t=Mvmyyo78nc1YakaX-0))
- [ ] In RTL Mode when expanded the settings doesnt work https://github.com/infor-design/enterprise-wc/issues/1226#issuecomment-1683601386

**Minor:**

- [ ] Enhance IdsModuleNavItem's support for 6-level-deep accordion nesting
- [x] Check hover state on IdsSearchField when filtering is active vs when it's not

**Comment by jbrcna** [comment]
`App Icon:` Failing in safari. notice that the icon is off.
Also, **hamburger menu** is not visible. **ids-module-nav-bar** overlaps dropdown
<img width="668" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/89fc0233-1fbf-4285-8181-c57ca9b76e68">
 
all browser: when in collapsed mode you have to click twice on hamburger menu to expand
https://github.com/infor-design/enterprise-wc/assets/56722184/07c17862-53e4-4550-bc6a-fe627e16917c


unable to expand using dropdown

https://github.com/infor-design/enterprise-wc/assets/56722184/10e83297-6525-4986-9c8d-12e6e54e7953

**Comment by tmcconechy** [comment]
@jbrcna I think we need to add the new mobile behavior and it will address this later I made a point on https://github.com/infor-design/enterprise-wc/issues/1518 to address this

**Comment by jbrcna** [comment]
thanks @tmcconechy
