### ISSUE TITLE
IdsDataGrid: Add personalization dialog

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1449]
**Describe the Enhancement**
Add a way for users to control the columns in the datagrid like on the .. menu on https://main-enterprise.demo.design.infor.com/components/datagrid/example-index.html

**Tasks**

- [ ] Review with design for updates
- [ ] Dialog should be updatable via slots/template or setting
- [ ] Options for title
- [ ] Add ability to not show some columns in the dialog
- [ ] Review backlog for other ideas
- [ ] Dont use toolbar idea, have an api to open the dialog

**Additional context**

See also: https://github.com/infor-design/enterprise/issues/7877 for some more context.

**Comment by hey-yall** [comment]
Hey @tmcconechy ! Can you ping @talkaboutdesign for more information about this issue? He needs a little more info for solutioning. Thanks!

**Comment by inforandy** [comment]
finalized design here: https://www.figma.com/file/JZdeun4ht1IsqZpV9xAW8Y/Colors?type=design&node-id=660-14205&mode=design&t=sFmjlbtec56FgLUy-0
