### ISSUE TITLE
Angular: Make sure examples work with ngModel / add value accessor API

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1505]
**Describe the bug**
Test each of the components and make an example showing the following works

```html
<my-component ngDefaultControl [(ngModel)]="anyVariable"></my-component>
```

**Task**

- [ ] Add an example with every component that would use an ngModal value. (like ids-input, ids-lookup ect). Make sure its bindable.
- [ ] If its not may need a value and to omit an onChange callback and add a change event
- [ ] Add the ids-accessors.ts from @volante007 
- [ ] Add docs

**Additional context**
https://itnext.io/how-to-use-angular-ngmodel-and-ngforms-with-webcomponents-802bd9e1d3d7

**Comment by volante007** [comment]
A couple of other candidates I can think of, that currently don't work with this, are ids-switch and ids-checkbox. But maybe those are intended to exclusively use `checked` rather than `value` being true/false? Also ids-radio, but not really the same case there.

Just comparing with how the Angular component wrappers work, I understand that some usage will have to change inevitably :)

**Comment by tmcconechy** [comment]
Another idea is to generate this 

```
@Directive({
  selector: "ids-checkbox[ngModel]",
  standalone: true,
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => IdsCheckboxValueAccessor),
      multi: true,
    },
  ],
})
export class IdsCheckboxValueAccessor extends CheckboxControlValueAccessor { }
```

If we really have to, but this requires a wrapper like thing that we didn't want to do. If required we can generate them from 

https://teams.microsoft.com/l/message/19:b649a7c426e64e3dbedb0cc5202ce2d4@thread.skype/1697121957252?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1697121957252&teamName=IDS%20Enterprise%20Development&channelName=Web%20Components&createdTime=1697121957252

**Comment by volante007** [comment]
Here's what we're using so far

``` 
import { Directive, forwardRef } from "@angular/core";
import { DefaultValueAccessor, CheckboxControlValueAccessor, NG_VALUE_ACCESSOR, RadioControlValueAccessor } from "@angular/forms";

@Directive({
	selector: "ids-input[formControlName],ids-input[formControl],ids-input[ngModel],ids-textarea[formControlName],ids-textarea[formControl],ids-textarea[ngModel],ids-radio-group[formControlName],ids-radio-group[formControl],ids-radio-group[ngModel],ids-dropdown[formControlName],ids-dropdown[formControl],ids-dropdown[ngModel]",
	standalone: true,
	providers: [
		{
			provide: NG_VALUE_ACCESSOR,
			useExisting: forwardRef(() => IdsDefaultValueAccessor),
			multi: true,
		},
	],
})
export class IdsDefaultValueAccessor extends DefaultValueAccessor { }

@Directive({
	selector: "ids-checkbox[formControlName],ids-checkbox[formControl],ids-checkbox[ngModel],ids-switch[formControlName],ids-switch[formControl],ids-switch[ngModel]",
	standalone: true,
	providers: [
		{
			provide: NG_VALUE_ACCESSOR,
			useExisting: forwardRef(() => IdsCheckboxValueAccessor),
			multi: true,
		},
	],
})
export class IdsCheckboxValueAccessor extends CheckboxControlValueAccessor { }

@Directive({
	selector: "ids-radio[formControlName],ids-radio[formControl],ids-radio[ngModel]",
	standalone: true,
	providers: [
		{
			provide: NG_VALUE_ACCESSOR,
			useExisting: forwardRef(() => IdsRadioValueAccessor),
			multi: true,
		},
	],
})
export class IdsRadioValueAccessor extends RadioControlValueAccessor { }
```

Then simply declare these on an Angular module, and export them if that module is a common, reusable one. 

With these in use, `[(ngModel)]` (or `formControl`) works fine for `ids-input`, `ids-dropdown`, `ids-textarea`, `ids-radio-group`, `ids-radio` and `ids-checkbox`. Currently there is some issue with `ids-switch` which doesn't work with the checkbox control value accessor for some reason, but that's being looked at by @clayinfor already

**Comment by clayinfor** [comment]
```javascript
import { Directive, forwardRef } from "@angular/core";
import { DefaultValueAccessor, CheckboxControlValueAccessor, NG_VALUE_ACCESSOR, RadioControlValueAccessor } from "@angular/forms";

@Directive({
  selector: `
    ids-input[formControlName],ids-input[formControl],ids-input[ngModel],
    ids-textarea[formControlName],ids-textarea[formControl],ids-textarea[ngModel],
    ids-dropdown[formControlName],ids-dropdown[formControl],ids-dropdown[ngModel],
    ids-lookup[formControlName],ids-lookup[formControl],ids-lookup[ngModel],
    ids-radio-group[formControlName],ids-radio-group[formControl],ids-radio-group[ngModel],
    ids-search-field[formControlName],ids-search-field[formControl],ids-search-field[ngModel],
    ids-spinbox[formControlName],ids-spinbox[formControl],ids-spinbox[ngModel],
    ids-color-picker[formControlName],ids-color-picker[formControl],ids-color-picker[ngModel],
    ids-date-picker[formControlName],ids-date-picker[formControl],ids-date-picker[ngModel],
    ids-time-picker[formControlName],ids-time-picker[formControl],ids-time-picker[ngModel],
    ids-upload[formControlName],ids-upload[formControl],ids-upload[ngModel],
    ids-upload-advanced[formControlName],ids-upload-advanced[formControl],ids-upload-advanced[ngModel],
  `,
  standalone: true,
  providers: [
    {
      // @see https://angular.io/errors/NG01203#ng01203-you-must-register-an-ngvalueaccessor-with-a-custom-form-control
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => IdsDefaultValueAccessor),
      multi: true,
    },
  ],
})
export class IdsDefaultValueAccessor extends DefaultValueAccessor { }

@Directive({
  selector: `
    ids-checkbox[formControlName],ids-checkbox[formControl],ids-checkbox[ngModel],
    ids-checkbox-group[formControlName],ids-checkbox-group[formControl],ids-checkbox-group[ngModel],
    ids-switch[formControlName],ids-switch[formControl],ids-switch[ngModel],
  `,
  standalone: true,
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => IdsCheckboxValueAccessor),
      multi: true,
    },
  ],
})
export class IdsCheckboxValueAccessor extends CheckboxControlValueAccessor { }

@Directive({
  selector: `
    ids-radio[formControlName],ids-radio[formControl],ids-radio[ngModel],
  `,
  standalone: true,
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => IdsRadioValueAccessor),
      multi: true,
    },
  ],
})
export class IdsRadioValueAccessor extends RadioControlValueAccessor { }
```

**Comment by clayinfor** [comment]
hey @volante007 , I have add the directive file you provided; thanks!  I've also updated it to support all of our custom input components. Please see the code-snippet above for final version.  You can also see the actual file in our examples repository [here](https://github.com/infor-design/enterprise-wc-examples/pull/38/files#diff-0927accf51b597d33d177ad269d8acb4f9d605a3a510e995006a16985598e4c2).

**Comment by volante007** [comment]
Thanks @clayinfor !

Unfortunately, we have seen some problems with our value accessors in an optimized production build. I suspect that Angular's value accessors, which we extend, are not present in `@angular/forms` when optimized. This is very unfortunate if true. We'll need to investigate this a bit more, but just a heads up..

cc @tmcconechy

**Comment by volante007** [comment]
We implemented the constructors including `super()` calls. Now works fine in optimized production build. So if you see the same errors in your Angular examples app (using `ng serve --configuration production`), try this:

```
...
export class IdsDefaultValueAccessor extends DefaultValueAccessor {
	constructor(renderer: Renderer2, elementRef: ElementRef) {
		super(renderer, elementRef, false);
	}
}

...
export class IdsCheckboxValueAccessor extends CheckboxControlValueAccessor {
	constructor(renderer: Renderer2, elementRef: ElementRef) {
		super(renderer, elementRef);
	}
}
```

Unfortunately, we couldn't satisfy the base constructor for `RadioControlValueAccessor`, as it depends on an internal. But, maybe we don't really need that accessor at all. Using `ngModel` on `<ids-radio-group>` instead of individual `<ids-radio>`s makes more sense IMO, and radio group uses the default one.

**Comment by tmcconechy** [comment]
@clayinfor what do you think? Do we need to update anything?

**Comment by jbrcna** [comment]
i am getting errors in console.
verified in https://main.wc.design.infor.com/ids-form/example.html
<img width="1717" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/d40f7374-e4e8-44c5-b18e-8c4ec4a7a054">

**Comment by clayinfor** [comment]
Hi @jbrcna , thanks for your feedback.  Could you please provide steps to reproduce the errors you were seeing? I was unable to reproduce.

**Comment by clayinfor** [comment]
Many thanks for your feedback, @volante007!!  I have updated our Angular examples repository to reflect your findings.

cc: @tmcconechy

**Comment by jbrcna** [comment]
> Hi @jbrcna , thanks for your feedback. Could you please provide steps to reproduce the errors you were seeing? I was unable to reproduce.


 the steps I did on the issue above is I just change the value & fill in the fields with some text. select from dropdown & radio and turn on switch. tried to trigger validation as well

I am unable to replicate @clayinfor . this is what I see now. 
when I go to ids-form Example pages. there were no links
<img width="684" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/4383a21c-b806-4ecc-9900-5587920f8437">

when I go to https://main.wc.design.infor.com/ids-form/example.html
<img width="1712" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/c62d6575-9ee2-4649-a499-6bb300b94fb1">

**Comment by tmcconechy** [comment]
@jbrcna sometimes the main. site has issues. Seems ok now. Can you retry? Or try localhost if future issues

**Comment by jbrcna** [comment]
thanks for clarifying @tmcconechy .
this is now working on my end as well.
<img width="1699" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/9c93618c-4150-40db-a981-e4a01a70d853">

I can also see the Example page
<img width="1166" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/85946179-2fd4-4c17-87bb-7e6d41cd08b8">

marking this test as Passed.
 @clayinfor
