### ISSUE TITLE
ReactTs: Updates to react TS example

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1651]
**Describe the bug**

Noting some bugs in this demo app for correction.

**Tasks**

- [ ] All dependencies updated to lates
- [ ] Switch App Menu to module nav
- [ ] try module nav on reduced screen width
- [ ] Add locale switcher/theme switcher
- [ ] http://localhost:3000/ids-lookup -> cant select rows
- [ ] http://localhost:3000/ids-date-picker -> picker opens in wrong position
- [ ] Test every page for issues

**Expected behavior**
Complete above

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**
