### ISSUE TITLE
IdsContainer: Remove Padding and make it a setting

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#242]
**Describe the bug**
The general idea is to remove the internal padding from ids-container so things like ids-header that have 100% height and width will stretch to the outside. This should be the default

**Tasks**

- [x] Make this padding a setting https://github.com/infor-design/enterprise-wc/blob/main/src/ids-container/ids-container.scss#L16 and remove
- [x] Add new setting (suggest simply padding) https://github.com/infor-design/enterprise-wc/blob/main/src/ids-container/ids-container.js#L60 that is an number. But generally would use 8, 16, 32, default is zero/none
- [x] Add doc for it
- [x] Add test for it
- [x] Confirm ids-header works as expected

**Expected behavior**
N/A
