### ISSUE TITLE
IdsLayoutGrid - Add more settings and features

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#298]
**Describe the Enhancement**

Add some more features to ids-layout-grid

**Tasks**

- [x] Add `minColWidth` property. For auto-responsive grids that use `auto-fit` and `minmax` there could be a setting to control where the reflow happens `<ids-layout-grid minColWidth="120px">`
- [x] Make `--grid-min-col-width` at https://github.com/infor-design/enterprise-wc/blob/main/src/ids-layout-grid/ids-layout-grid.scss#L17 a setting
- [x] Add the following columns and breakpoints:
   - XXL 1440px —  12 columns, 24px gutter, 24px margin 
   - XL 1280px — 12 columns,  24px gutter, 24px margin 
   - L 1024px — 12 columns,  16px gutter, 16px margin
   - M 840px — 8 columns, 16px gutter, 16px margin 
   - S 600px — 4 columns, 16px gutter, 16px margin
   - XS 360px — 4 columns, 16px gutter, 16px margin
- [x] Optional 16 column grid XL & above
- [x] Update Readme with new settings
