### ISSUE TITLE
IdsAbout: Remaining Features/Issues

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#499]
**Description**
Lists the Remaining Bugs/Features for a 100% Component

**Major**

- [ ] Add a test to ensure the `show/hide` of modal are omitted see (#489)[https://github.com/infor-design/enterprise-wc/issues/498]

**Minor**

- [ ] Add a test (not an example) to ensure another modal can be opened from the contents of the about modal (see)[https://main-enterprise.demo.design.infor.com/components/about/test-nested.html]
- [ ] Add a side by side example
- [x] Add a way to set test attributes on the component (id/data-automation-id)[depends on #145][https://github.com/infor-design/enterprise-wc/issues/145]

**Additional context**
Original Issue #308
