### ISSUE TITLE
IdsActionSheet: Remaining Features/Issues

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#504]
**Description**
Lists the Remaining Bugs/Features for a 100% complete component

**Major**

- [ ] Rename `btnText` to `cancelBtnText` and make it update live (https://github.com/infor-design/enterprise-wc/issues/505)
- [ ] Keyboard is a bit wierd as you need to tab to the cancel button (all arrow keys should work) (https://github.com/infor-design/enterprise-wc/issues/505)

**Minor**

- [ ] Add Tray feature to Action Sheet but this may not be needed as could be replaced by floating action buttons.
- [ ] Add visual test for having no cancel button (https://github.com/infor-design/enterprise-wc/issues/505)

**Additional context**
Original Issue #406

**Comment by celhalal** [comment]
Similar features/issues mentioned in closed ticket #505
