### ISSUE TITLE
IdsAxisChart: Remaining Features/Issues

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#515]
**Original Issue** #400 

**Major**

- [x] #733
- [ ] #734
- [x] #738
- [x] Chart Types: Line Chart
- [x] Chart Types: Area Chart
- [x] Chart Types: Bar Chart
- [x] Chart Types: Stacked Column Chart
- [x] Chart Types: Column Chart
- [x] Chart Types: Step Chart
- [x] Chart Types: Pie Chart
- [ ] Chart Types: Grouped Column Chart
- [ ] Chart Types: Grouped Bar Chart
- [ ] Chart Types: Stacked Bar Chart
- [ ] Chart Types: Scatter Plot Chart
- [ ] Rendering: Negative Values (bar/line)

**Minor**

- [ ] Add svg patterns and accessibility to line, area, bar stacked
- [ ] Add accessibility once confirmed to area and line chart (only in bar now until tested) https://github.com/infor-design/enterprise-wc/commit/f6014597004ab7963ef66449bea63bfc43e95fa0
- [ ] Maybe: Have a table option to actually display the data in optional data form
- [ ] Add side by side examples and responsive examples
- [ ] Chart Types: Bubble Chart
- [ ] Chart Types: Positive Negative ( Negative Values with comparison / slightly different chart)
