### ISSUE TITLE
IdsAppMenu: Remaining Features/Issues

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#516]
**Description**
Lists the Remaining Bugs/Features for a 100% Component

**Minor**

- [ ] Implement more efficient system for filter-then-collapse behavior (make it collapse panels with no filtered children)
- [ ] Complete IdsHighlight utility and implement against matching text in accordion headers. (infor-design/enterprise-wc#494)
- [ ] Personalization (colored menu) - do we need it?
- [ ] Roll Switcher - has several designs need to land on one first
- [ ] Add a test to ensure the `show/hide` of modal are omitted see (#489)[https://github.com/infor-design/enterprise-wc/issues/498]
- [ ] Further keyboard testing/verification

**Additional context**
Original Issue #323
