### ISSUE TITLE
IdsBadge: Remaining Features/Issues

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#517]
**Description**
Lists the Remaining Bugs/Features for a 100% Component

**Minor**

- [ ] The contrast theme has the wrong colors with bad contrast [see](https://main.wc.design.infor.com/ids-badge) and switch to contrast https://github.com/infor-design/enterprise-wc/issues/518
- [ ] Some size changes on [5608](https://github.com/infor-design/enterprise/issues/5608) may be relevant when this is completed.
- [ ] Missing css only example https://github.com/infor-design/enterprise-wc/issues/518

**Additional context**
Original Issue #41
