### ISSUE TITLE
IdsBreadCrumb: Remaining Features/Issues

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#526]
**Description**
Lists the Remaining Bugs/Features for a 100% Component

**Major**

- [ ] Add expanded [hit box](https://main-enterprise.demo.design.infor.com/components/breadcrumb/example-with-hitbox.html)
- [ ] Add [truncated feature](https://main-enterprise.demo.design.infor.com/components/breadcrumb/example-navigation-breadcrumbs.html)
- [ ] Add example for [header bread crumbs example](https://main-enterprise.demo.design.infor.com/components/breadcrumb/example-navigation-breadcrumbs.html) https://github.com/infor-design/enterprise-wc/issues/527
- [ ] Add example for [sitting in a toolbar example](https://main-enterprise.demo.design.infor.com/components/breadcrumb/test-flex-toolbar.html) https://github.com/infor-design/enterprise-wc/issues/527

**Minor**

- [ ] Add a test for click events on the links (callback example) https://github.com/infor-design/enterprise-wc/issues/527
- [ ] In RTL mode are the slashes the right direction? https://github.com/infor-design/enterprise-wc/issues/527
- [ ] In dark mode the slashes are hard to see (confirm) https://github.com/infor-design/enterprise-wc/issues/527

**Additional context**
Original Issue #208

**Comment by jeffwa428** [comment]
@tmcconechy 
I have checked bootstrap RTL breadcrumb example. It seems like slash direction is correct.

![image](https://user-images.githubusercontent.com/94501186/157146801-ae029360-1e80-440e-8259-fa1001d19ee2.png)

**Comment by tmcconechy** [comment]
ok thanks @jeffwa428 lets leave this for now as im not sure https://material.io/design/usability/bidirectionality.html#mirroring-elements -> mentions not doing it for icons

Asking the translator team @cpinatel7 -> in RTL mode should slashes in the breadcrumb go the opposite way...
