### ISSUE TITLE
IdsButton: Remaining Features/Issues

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#531]
**Description**
Lists the Remaining Bugs/Features for a 100% Component

**Major**

- [ ] Add a 100% (responsive button) example like the [old version](https://main-enterprise.demo.design.infor.com/components/button/example-100-percent.html) https://github.com/infor-design/enterprise-wc/issues/532

**Minor**

- [ ] Add the secondary border button (also called outline button in bootstrap) see [old version](https://main-enterprise.demo.design.infor.com/components/button/test-secondary-border.html)
- [ ] Dispatch events to the parent for better delegation
- [ ] API method/prop for toggling the `.audible` class on the text span
- [ ] API method/prop for re-arranging the order of named text/icon slots?
- [ ] get/set value() from menu? (store/report menu's current value)
- [ ] "is-open" state or `button.popup.visible`
- [ ] make it open a popup (maybe call this `IdsPopupButton`?)
- [ ] Add a link that looks like a button (responsive button) example like the [old version]https://main-enterprise.demo.design.infor.com/components/button/example-as-link.html)

**Additional context**
Original Issue #12

**Comment by tmcconechy** [comment]
This is out dated.
