### ISSUE TITLE
IdsCard: Make a linkable actionable card

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#550]
**Describe the bug**
Need a way to set an actionable card to be a hyperlink (or a button as it is now).

**Task**

- [ ] Add an actionable link card on https://main.wc.design.infor.com/ids-card/
- [ ] If actionable is set and you add a href (and optional target) it renders as a link instead
- [ ] Fix styling so it can take the height of the contents (if auto-height = "true") see: https://github.com/infor-design/enterprise-wc/blob/main/demos/example.js#L180
- [x] Update https://main.wc.design.infor.com/ to use it (will be fixed by #239 )

**Additional context**
https://github.com/infor-design/enterprise-wc/issues/280
