### ISSUE TITLE
IdsColorPicker: Remaining Features/Issues

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#551]
**Description**
Lists the Remaining Bugs/Features for a 100% Component

**Major**

- [ ] https://main-enterprise.demo.design.infor.com/components/editor/example-index.html - editor version
- [x] Fix the keyboard (arrow down , enter, keys around the colors ect), and fix focus state around swatches
- [x] Tooltip on the colors
- [x] Fix all the states [See example](https://main-enterprise.demo.design.infor.com/components/dropdown/test-states.html) and [also see](https://main-enterprise.demo.design.infor.com/components/colorpicker/test-states.html)
- [x] Check Styles match with 4.x on the popup container - swatch/hover/spacing/selected state on swatches
- [x] Default color list should load from our theme palette `node_modules/ids-identity/dist/theme-new/tokens/web/ui.config.color-palette.js`
- [x] Check mark color should change based on swatch background (check mark color can get from colorlist -arrowClass)
- [ ] Standardize/Abstract out Popup/Picker/"return value" interface (to be used in this and other pickers)
- [x] Check JSDoc comments for everything that's missing
- [x] Add test for change event firing
- [x] Add test for setting color / clearing color
- [x] Change hide/show to open/close for consistency and make sure it fires events that are documented
- [x] Ability to set custom labels for selections. Should be able to show color-name `azure06` or `color-hex` `#ffffff` inside the input. [See example](https://main-enterprise.demo.design.infor.com/components/colorpicker/example-custom-labels.html)
- [x] Show label instead of hex. [See example](https://main-enterprise.demo.design.infor.com/components/colorpicker/example-show-label.html)
- [x] Add sizes widths and field heights. [See Ids Input](https://main.wc.design.infor.com/ids-input/)
- [x] Add dirty tracker example to [the example page](https://main.wc.design.infor.com/ids-color-picker/)

**Minor**

- [ ] Some text hard coded in component, should give setting/slots to user change those text strings ids-text audible="true"
- [ ] Enable/Disable standard HTML colorpicker independently of other colorpicker parts using a boolean attribute
- [ ] Click the swatch to select / option for the "advanced" picker
- [ ] Add side by side example
