### ISSUE TITLE
IdsContextualActionPanel: Remaining Features/Issues

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#553]
**Description**
Lists the Remaining Bugs/Features for a 100% Component

**Major**
- [x] Mobile styles (need to rework Modal for this) [#5607](https://github.com/infor-design/enterprise/issues/5607)
- [x] #728

**Minor**
- [ ] Side by side example
- [ ] Make RTL Work better (icon buttons)
