### ISSUE TITLE
IdsDatagrid: Remaining Features/Issues

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#555]
**Description**
Lists the Remaining Bugs/Features for a 100% Component

**Major**

- [x] Hidden Columns
- [x] Column Sizes/Widths
- [x] Column Reorder
- [x] Frozen Columns
- [x] cellNavigation with keyboard and setting https://github.com/infor-design/enterprise-wc/issues/737
- [x] disableClientFilter setting https://github.com/infor-design/enterprise-wc/issues/737
- [x] Place popupmenu in the root of the grid so it will not be cut off for filtering
- [x] #1021
- [x] Fix icon and field sizes on http://localhost:4300/ids-data-grid/filter.html
- [x] Save Settings [example](https://main-enterprise.demo.design.infor.com/components/datagrid/test-save-settings.html) https://github.com/infor-design/enterprise-wc/issues/737
- [x] Empty Message [example](https://main-enterprise.demo.design.infor.com/components/datagrid/example-empty-message.html) https://github.com/infor-design/enterprise-wc/issues/648
- [x] Expandable Row [example](https://main-enterprise.demo.design.infor.com/components/datagrid/example-expandable-row.html) https://github.com/infor-design/enterprise-wc/issues/737
- [ ] Export Csv and Xls [example](https://main-enterprise.demo.design.infor.com/components/datagrid/example-export-from-button.html) https://github.com/infor-design/enterprise-wc/issues/153
- [x] Grouped Headers [example](https://main-enterprise.demo.design.infor.com/components/datagrid/example-grouped-headers.html)
- [ ] Toolbar [example](https://main-enterprise.demo.design.infor.com/components/datagrid/example-custom-toolbar.html)
- [x] Editors / Editing / Dirty [example](https://www.w3.org/TR/wai-aria-practices/examples/grid/dataGrids.html) including https://github.com/infor-design/enterprise/issues/6338 and a way to veto selection [example](https://main-enterprise.demo.design.infor.com/components/datagrid/example-beforeselect-veto.html) https://github.com/infor-design/enterprise-wc/issues/737
- [x] Keyboard Navigation (included tabbable/not tabbable) see [standards](https://www.w3.org/TR/wai-aria-practices/#keyboard-interaction-for-layout-grids) (actionable mode, X cell navigation, X row navigation)
- [ ] More Accessibility see [standards](https://design.infor.com/code/ids-enterprise/latest/listview#accessibility)
- [ ] Disabled Rows  and cells[example](https://main-enterprise.demo.design.infor.com/components/datagrid/example-disabled-rows.html) test on http://localhost:4300/ids-data-grid/columns-formatters.html with disabled checkboxes https://github.com/infor-design/enterprise-wc/issues/737
- [ ] Grouped Rows [example](https://main-enterprise.demo.design.infor.com/components/datagrid/example-grouping-filter.html)
- [x] Tooltips [example](https://main-enterprise.demo.design.infor.com/components/datagrid/tooltips.html) https://github.com/infor-design/enterprise-wc/issues/737
- [x] Tree [example](https://main-enterprise.demo.design.infor.com/components/datagrid/example-tree.html) https://github.com/infor-design/enterprise-wc/issues/737
- [x] Text align headers and cells [example](https://main-enterprise.demo.design.infor.com/components/datagrid/test-alerts-right-align.html)
- [x] Css class/Colors
- [x] Custom Formatters and Editors Example https://github.com/infor-design/enterprise-wc/issues/737
- [x] Context Menu https://github.com/infor-design/enterprise-wc/issues/737
- [x] Ability to set icon and tooltip for it on the header
- [ ] scrollRowIntoView https://github.com/infor-design/enterprise-wc/issues/737

**Minor**

- [ ] Row Reorder [example](https://main-enterprise.demo.design.infor.com/components/datagrid/example-row-reorder.html)
- [ ] Keyword Search [example](https://main-enterprise.demo.design.infor.com/components/datagrid/example-keyword-search.html)
- [ ] Nested Datagrid [example](https://main-enterprise.demo.design.infor.com/components/datagrid/example-nested-grids.html)
- [ ] Editor Placeholder [example](https://main-enterprise.demo.design.infor.com/components/datagrid/example-placeholder.html)
- [x] #1029
- [ ] Paste/Copy from Excel [example](https://main-enterprise.demo.design.infor.com/components/datagrid/test-copy-paste-from-excel.html)
- [ ] Summary Row [example](https://main-enterprise.demo.design.infor.com/components/datagrid/test-summary-row-pager.html)
- [x] Automation id's
- [ ] Errors and Validation
- [ ] Xss Tests
- [ ] Colspans [example](https://main-enterprise.demo.design.infor.com/components/datagrid/example-colspan.html)
- [ ] Column Groups with Frozen Columns
- [ ] Optimize the row recycling in virtual scroll (load from top or bottom only)
- [ ] Column Template
- [ ] personalization dialog (maybe)
