### ISSUE TITLE
IdsDatepicker: Remaining Features/Issues

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#562]
**Description**
Lists the Remaining Bugs/Features for a 100% Component

**Major**
- [x] Code to new designs https://www.figma.com/file/DnguXUS7T4J5Rce92MuoCY/?node-id=892%3A348 and 
https://www.figma.com/file/y1oT4NPGJA78EzUNssZYsG/Calendar?node-id=1%3A2269&viewport=-288%2C2528%2C0.32999536395072937
- [x] Add Masking / Localization with way to customize or disable the mask
- [x] Keyboard Shortcuts according to https://github.com/infor-design/enterprise/blob/main/src/components/datepicker/readme.md#keyboard-shortcuts https://github.com/infor-design/enterprise-wc/issues/538
- [x] General accessibility (screen reader) / axe https://github.com/infor-design/enterprise-wc/issues/538
- [x] Clicking the month/year opens the month and year selection panel https://github.com/infor-design/enterprise-wc/issues/538
- [x] Configurable legend https://main-enterprise.demo.design.infor.com/components/datepicker/example-legend.html https://github.com/infor-design/enterprise-wc/issues/538
- [x] Range picker https://main-enterprise.demo.design.infor.com/components/datepicker/example-range.html including https://main-enterprise.demo.design.infor.com/components/datepicker/test-week-picker.html https://github.com/infor-design/enterprise/blob/main/src/components/datepicker/datepicker.js#L69-L79 https://github.com/infor-design/enterprise-wc/issues/538
- [x] Make it open faster (seems a little slow and for @EdwardCoyle it was 2-3 seconds) https://github.com/infor-design/enterprise-wc/issues/538
- [x] Add functional tests for these cases https://main-enterprise.demo.design.infor.com/components/datepicker/example-anniversary-format.html and https://main-enterprise.demo.design.infor.com/components/datepicker/example-custom-format.html
- [x] Add disabled dates https://main-enterprise.demo.design.infor.com/components/datepicker/example-disabled-dates.html for month view as well. Can rethink the API see current settings https://github.com/infor-design/enterprise/blob/main/src/components/datepicker/datepicker.js#L40-L57
- [x] Add sizes and field height examples like input https://main-enterprise.demo.design.infor.com/components/datepicker/example-sizes.html with tests
- [x] Date picker with time https://main-enterprise.demo.design.infor.com/components/datepicker/example-timeformat.html with tests see settings https://github.com/infor-design/enterprise/blob/main/src/components/datepicker/datepicker.js#L26-L31
- [x] Add tests for invalid dates https://main-enterprise.demo.design.infor.com/components/datepicker/example-validation.html
- [x] Add test that the change and input event is fired when the date is changed as a test. And make sure the hide/show events are fired as well (from the popup component). And add to breaking changes.
- [x] Add test that the placeholder works (should work)
- [x] Add test for UTC picker https://github.com/infor-design/enterprise/blob/main/src/components/datepicker/datepicker.js#L83
- [x] Speed -> if you run the performance tab https://main-enterprise.demo.design.infor.com/components/datepicker/example-index.html is about 10 times slower rendering the page

**Minor**
- [x] Add week numbers when design approved https://github.com/infor-design/enterprise/issues/5785
- [x] Add mobility changes when design approved https://github.com/infor-design/enterprise/issues/5763 (some need to be confirmed)
- [x] Add test for this case https://github.com/infor-design/enterprise/issues/5255
- [x] Add side by side example
- [x] Figure out https://main-enterprise.demo.design.infor.com/components/datepicker/example-month-year-format.html if needed?

**Comment by EdwardCoyle** [comment]
Regarding this one:

> Make it open faster (seems a little slow and for @EdwardCoyle it was 2-3 seconds) https://github.com/infor-design/enterprise-wc/issues/538

This could be something in IdsDatePicker, but there's also a known problem in IdsPopup where it's not possible to bypass the "wait for open" needed for animations to complete when animations are disabled.  This may contribute to the perceived wait.  I bring this up here because that part is probably separate from the IdsDatePicker part.

**Comment by tmcconechy** [comment]
@andriivarhanov in addition there is some new designs that we should style towards https://www.figma.com/file/DnguXUS7T4J5Rce92MuoCY/?node-id=892%3A348

**Comment by andriivarhanov** [comment]
@tmcconechy 
I have some questions about the remaining items:

> Add week numbers when design approved [Calendar: Week number required on views/date-time selection. enterprise#5785](https://github.com/infor-design/enterprise/issues/5785)

I can’t find if it was approved
***
> Add mobility changes when design approved [Datepicker/Calendar: Mobile and Usability Improvements enterprise#5763](https://github.com/infor-design/enterprise/issues/5763) (some need to be confirmed)

it looks like it’s the same as 

> Code to new designs https://www.figma.com/file/DnguXUS7T4J5Rce92MuoCY/?node-id=892%3A348 and
https://www.figma.com/file/y1oT4NPGJA78EzUNssZYsG/Calendar?node-id=1%3A2269&viewport=-288%2C2528%2C0.32999536395072937

what is ready mostly except for mobile equivalent and mobile related items:

- Horizontal swiping for calendar view navigation
- Vertical swiping for month / year navigation
- For mobile action sheet, add a variant that includes a ‘Cancel’ action in case it is not apparent that users can tap away to ‘Cancel’.

should I do mobile view?
***
> Fix bug https://github.com/infor-design/enterprise/issues/4605

it looks like it's related to `ids-popup`, could be shared functionality, should I add it to the popup component?

**Comment by tmcconechy** [comment]
@andriivarhanov to answer those questions:

> Add week numbers when design approved https://github.com/infor-design/enterprise/issues/5785
Wasn't yet but I dont see why it wont be. You can either skip it for now and we make an issue or add it as an option assume it will be.

> it looks like it’s the same as
Ok, yes in https://github.com/infor-design/enterprise/issues/5763 i tried to parse the design and mention the changes but you can just go with the design for now. The main thing is the month/year picker improvements for me but there is some other nice stuff in there. 

Its ok to skip some of it like:
- Horizontal swiping for calendar view navigation
- Vertical swiping for month / year navigation
- For mobile action sheet, add a variant that includes a ‘Cancel’ action in case it is not apparent that users can tap away to ‘Cancel’.

Especially the last one which i dont really agree with. 

> it looks like it's related to ids-popup, could be shared functionality, should I add it to the popup component?
Sure please add if you have a fix. If not we can wait for that issue to be fixed and try later?

**Comment by andriivarhanov** [comment]
@tmcconechy thanks for the answers, I will include week numbers to the issue and let's create another issue for 

> Fix bug https://github.com/infor-design/enterprise/issues/4605

time picker and color picker can use the functionality as well so it's going to be mixin or ids-popup setting option

**Comment by tmcconechy** [comment]
ok sounds good @andriivarhanov - does https://github.com/infor-design/enterprise/issues/4605 cover the case?
If not just add some steps to that issue or a new entire issue depending on how close you think they are...

**Comment by andriivarhanov** [comment]
@tmcconechy yeah, https://github.com/infor-design/enterprise/issues/4605 covers the issue, steps to reproduce are correct as well as expected behavior
