### ISSUE TITLE
IdsWizard: Remaining Features/Issues

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#570]
**Original issue:** #126

**Major**

- [ ] Re-evaluate current solution and try to simplify existing features
- [ ] Add `onStepChange` callback for step changes by user interaction or programmatically
- [ ] Implement Change to short labels on lower sizes (alternate, shorter text string applied using a different attribute on IdsWizardStep -- `short-label`?)
- [ ] Add an attribute for disabling URI-hash changes when steps are clicked (`no-link`?)
- [ ] Test screen reader/accessibility (should be similar to tabs) and fix/create ARIA attributes
- [ ] Add theme support (move current colors into `&[mode="light"]` theme, add dark/contrast colors, and implement Theme Mixin)
- [ ] Remove the urls on it (they show undefined)

**Minor**

- [ ] Do not use wait() in wizard test logic for rendered() in Jest - replace with [page.waitFor](https://puppeteer.github.io/puppeteer/docs/puppeteer.page.waitfor) or another built-in
- [ ] Add standalone CSS examples and related styles
