### ISSUE TITLE
IdsDraggable/Swapable: Remaining Features/Issues

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#587]
**Description**
Lists the Remaining Bugs/Features for a 100% Component

**Major**

- [ ] Support mobile touch
- [ ] Support for dragging datagrid columns (is clone needed)
- [ ] Does it need keyboard support
- [x] Document: ids-drag event: e.detail.parentRect, e.detail.dragDeltaX/Y, e.detail translateX/Y
- [x] Fix known issue (minor): in firefox, the cursor when moved quickly flashes between dragging/default as the positioning/detection isn't instant as it is in chrome.
- [x] Support for dragging with handles (row reorder)
- [x] http://localhost:4300/ids-list-view/sortable.html -> use the new one
- [x] http://localhost:4300/ids-list-builder -> use the new one
- [x] compare styling with the latest https://main-enterprise.demo.design.infor.com/components/swaplist/example-index.html  (header seems too big for one thing)

**Additional context**
Original Issue #272

**Comment by jmacaluso711** [comment]
Can explore using this [shim](https://github.com/justinribeiro/html5-dragdroptouch-shim/blob/master/src/dataTransfer.js) for touch capability

**Comment by tmcconechy** [comment]
Closing this as stale issue
