### ISSUE TITLE
IdsDropdown: Remaining Features/Issues

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#601]
**Description**
Lists the Remaining Bugs/Features for a 100% Component

**Major**
- [x] Bug No initial value and you cant select see https://github.com/infor-design/enterprise-wc/issues/600
- [x] Groups like https://main-enterprise.demo.design.infor.com/components/dropdown/example-groups.html
- [x] Placeholder / Blank Item
- [x] #759
- [x] #758
- [x] Add all size examples like https://main-enterprise.demo.design.infor.com/components/dropdown/example-widths.html (width and height) #674
- [x] Check themes with old version (dark theme is incorrect) see https://github.com/infor-design/enterprise-wc/issues/600

**Minor**

- [x] Bug when opening it in the slight wrong position
- [x] Test duplicate values/labels
- [x] Text xss like https://main-enterprise.demo.design.infor.com/components/dropdown/test-xss.html
- [x] Add events or funnel events from the popup when it opens and closes
- [x] Make sure open issues get in when fixed https://github.com/infor-design/enterprise/issues?q=is%3Aissue+is%3Aopen+dropdown

**Maybe in the Future**
- [ ] Virtual Scrolling

**Comment by danielortiz1982** [comment]
@andriivarhanov We are currently in Sprint planning, when you have a moment can you please provide an update on this issue along with what's remaining.

Thanks!

**Comment by andriivarhanov** [comment]
@danielortiz1982 from the major items remaining are groups and placeholder - will be ready today or tomorrow, minor items will take a day or two so I think I will do PR with all the remaining item on Friday 19th, does it work or should I make the PR earlier?

**Comment by tmcconechy** [comment]
Just when its ready, no rush @andriivarhanov . Just trying to see if you need new issues.

**Comment by danielortiz1982** [comment]
@andriivarhanov Thanks for the update!

**Comment by jbrcna** [comment]
hello, typeahead is not working in safari browser. cc @CindyMercadoReyes 
https://main.wc.design.infor.com/ids-dropdown/groups.html
<img width="372" alt="image" src="https://user-images.githubusercontent.com/56722184/188627155-36e39245-c8ce-4a28-8dd9-55467ab46207.png">
https://main.wc.design.infor.com/ids-dropdown/typeahead.html
<img width="342" alt="image" src="https://user-images.githubusercontent.com/56722184/188627527-bc9acb34-5d5c-4a92-a99a-c6bbe7f77d84.png">
https://main.wc.design.infor.com/ids-dropdown/clearable.html
<img width="408" alt="image" src="https://user-images.githubusercontent.com/56722184/188627713-a1c18d5e-6ffb-45f0-95c1-4d7b249aa950.png">
