### ISSUE TITLE
IdsEditor: Remaining Features/Issues

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#602]
**Description**
Lists the Remaining Bugs/Features for a 100% Component

**Major**

- [ ] CSP error (mixed with style or html injection) see https://github.com/infor-design/enterprise-wc/issues/603
- [ ] un/order list (CSP error) also https://github.com/infor-design/enterprise-wc/issues/603
- [ ] add ids-color-picker (currently in use html `input[type="color"]` element)
- [ ] add preview mode ([see 4.x](https://main-enterprise.demo.design.infor.com/components/editor/example-preview.html))
- [ ] block quote
- [ ] hyperlink (model not open)
- [ ] insert image (model not open)

**Minor**

- [ ] custom modal templates (currently use default in built)
- [ ] custom source-formatter with and/or without custom theme (currently use default in built)
- [ ] output value as json format
- [ ] each action should be fully working (etc. `redo`, `undo`, `clear-formatting`, `un/ordered list`)
- [ ] find way to work without `document.execCommand(), document.queryCommandSupported(), document.queryCommandState()`
- [ ] write tests for more coverage
- [ ] safari need to fix below action issues (might issue with: `#getSelection()`)
- [ ] header(1-6)
- [ ] color picker (popup not open, could be just css styles -because currently made as hidden input)
- [ ] text align
