### ISSUE TITLE
IdsEmptyMessage/IdsErrorMessage: Remaining Features/Issues 

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#606]
**Description**
Lists the Remaining Bugs/Features for a 100% Component

**Major**

- [ ] Fix the sizing and padding to match the design changes on https://github.com/infor-design/enterprise/issues/6099 (pending)
- [ ] Add side by side example for both error message 
- [ ] Add side by side example for empty message
