### ISSUE TITLE
IdsFieldset: Remaining Features/Issues 

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#609]
**Description**
Lists the Remaining Bugs/Features for a 100% Component

**Major**

- [x] Styling is not the same on https://main.wc.design.infor.com/ids-fieldset/ as https://main-enterprise.demo.design.infor.com/components/fieldset/example-50-50.html (use ids-data-label and button icon on wrong side)
- [ ] Make the font size fixed size so it works on side-by-side.html `@include text-16()/text-14()` ect and in general make https://main.wc.design.infor.com/ids-fieldset/side-by-side.html work
- [ ] Add 50/50 example using the responsive grid https://main-enterprise.demo.design.infor.com/components/fieldset/example-50-50.html
