### ISSUE TITLE
Typescript: Conversion

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#612]
**Task**

Convert to using typescript

- [x] TS Loader
- [x] Convert some components (the rest for doing as a team)
- [x] Test prod build is good
- [x] Test demo app is good
- [x] Fix unit tests
- [x] Document conversion steps
