### ISSUE TITLE
IdsTree: Remaining Features/Issues

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#615]
**Original Issue:** #235 

**Major:**

- [x] #735
- [ ] Reorder/Sort (needs IdsDraggable) ([EP Example](https://main-enterprise.demo.design.infor.com/components/tree/example-sortable.html))
- [ ] Lazy-Load sub nodes with ajax ([EP Example](https://main-enterprise.demo.design.infor.com/components/tree/example-ajax.html))
- [ ] Add/Remove and Update single, multiple and all nodes
- [x] Standalone CSS Examples

**Minor:**

- [ ] Context menu (might be possible in an example) ([EP Example](https://main-enterprise.demo.design.infor.com/components/tree/example-context-menu.html))
- [ ] Possibly Editing https://github.com/infor-design/enterprise/issues/4442
- [ ] Counts auto/manually ([EP example](https://main-enterprise.demo.design.infor.com/components/tree/test-toggle-icon-and-count.html))
