### ISSUE TITLE
IdsHeader: Remaining Features/Issues

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#619]
**Description**
Lists the Remaining Bugs/Features for a 100% Component

**Major**

- [ ] The layout on https://main.wc.design.infor.com/ids-header/breadcrumb.html is wrong and should match https://main-enterprise.demo.design.infor.com/components/header/example-breadcrumbs.html
- [ ] Add record id and drill down example like https://main-enterprise.demo.design.infor.com/components/header/example-record-id.html
- [x] Add header tabs example like https://main-enterprise.demo.design.infor.com/components/header/example-tabs.html
- [x] Update search field styles like https://github.com/infor-design/enterprise/issues/6047
  and https://www.figma.com/file/gS5jIE14am8hYEvmtIAXLv/Search_Enhancements?node-id=209%3A2536
- [ ] Test design changes on https://github.com/infor-design/enterprise/issues/5700 and https://github.com/infor-design/enterprise/issues/5604

**Minor**

- [ ] Add side by side example
- [ ] Add menubutton example like https://main-enterprise.demo.design.infor.com/components/header/example-popupmenu.html
- [ ] Add wizard example like https://main-enterprise.demo.design.infor.com/components/header/example-wizard.html
- [ ] Add sticky header example (position sticky). This is new and used by landmark

**Additional context**
Original Issue #236
