### ISSUE TITLE
IdsToast: Remaining Features / Issues

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#635]
**Original Issue:** #129 

**Major**

- [ ] Accessibility Live Region in Shadow DOM
- [ ] Need to find the way to switch RTL or LTR with draggable and save-position, currently it goes off the window

**Minor**

- [ ] Standalone CSS examples
