### ISSUE TITLE
IdsImage: Remaining Features/Issues

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#654]
**Description**
Lists the Remaining Bugs/Features for a 100% Component

**Major**

- [ ] The icon color should be changeable with a setting
- [ ] Side by side example

**Minor**

- [ ] Add upload drag drop and crop as per https://github.com/infor-design/enterprise-wc/issues/653

**Additional context**
Original Issue #360
