### ISSUE TITLE
IdsListBuilder: Remaining Features/Issues

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#660]
**Description**
Lists the Remaining Bugs/Features for a 100% Component

**Major**

- [ ] Better keyboard support for all actions
- [ ] Can't create a new item if no items in the list initially
- [ ] Can multiselect but delete removes one at a time (select one, delete, select another, delete, select another, delete)
- [ ] Editing style needs design review
- [ ] Add same events as the prod component `move`, `selected`, `click`, `doubleclick` `change`, `add`, `beforeAdd`, `afterAdd`, `delete` `beforeDelete`, `afterDelete`
- [ ] Hover state in high contrast mode is 100% black

**Medium**

- [ ] Correct aria [see standards](https://design.infor.com/code/ids-enterprise/latest/listview#accessibility)
- [ ] A way to save order / events
- [ ] Make focus state on buttons white with box shadow
- [ ] More test coverage

**Additional context**
Original Issue #308
