### ISSUE TITLE
IdsListView: Remaining Features

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#661]
**Description**
Lists the Remaining Bugs/Features for a 100% Component

**Major**

- [x] Paging https://main-enterprise.demo.design.infor.com/components/listview/example-paging-clientside.html
- [x] Click and Dblclick events https://main-enterprise.demo.design.infor.com/components/listview/example-click-events.html
- [x] Disabled https://main-enterprise.demo.design.infor.com/components/listview/test-contextual-disabled.html with api or setting (conditionally)
- [x] Accessibility see [standards](https://design.infor.com/code/ids-enterprise/latest/listview#accessibility)
- [x] Event delegation on the click event
- [x] Add selection events (use selected) and fix selection styling https://main-enterprise.demo.design.infor.com/components/listview/example-events.html
- [x] Fix styling in the high contrast mode

**Minor**

- [x] Organize Embellishment / template classes like the ones here to float using ids-text and listview  https://main-enterprise.demo.design.infor.com/components/listview/example-alternate-row-color.html (skip alternate color) and links https://main-enterprise.demo.design.infor.com/components/listview/example-links.html and status https://main-enterprise.demo.design.infor.com/components/listview/example-status.html and actions https://main-enterprise.demo.design.infor.com/components/listview/test-actions-button.html
-  [x] https://main.wc.design.infor.com/ids-list-view/card.html example is broken
- [x] Add footer navigation bar https://main-enterprise.demo.design.infor.com/components/listview/example-footer-navigation.html (but make it smaller)
- [x] Add mixed and multiselect examples https://main-enterprise.demo.design.infor.com/components/listview/example-mixed-selection.html and https://main-enterprise.demo.design.infor.com/components/listview/example-multiselect.html
- [ ] #763

For Embellishment Classes i think the list is:
**hierarchy**
- [ ] heading
- [ ] heading-lg
- [ ] subheading
- [ ] subheading-lg
- [ ] micro
- [ ] mico-lg

**data**
- [ ] data
- [ ] text
- [ ] data-label

**other**
- [x] image
- [x] badge
- [x] status

**layout**
- [x] (flex) left and right
- [ ] table layout (css table flex)

**Additional context**
Original Issue #174

**Comment by tmcconechy** [comment]
This this can be closed for now as only one issue left
