### ISSUE TITLE
IdsListView: Add selection events and fix styling

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#662]
**Describe the bug**
Fix some of the features related to #661 and selecting/selection and events

**Tasks**

- [x] Fix styling in the high contrast mode (extra borders)
- [x] Click and Dblclick events https://main-enterprise.demo.design.infor.com/components/listview/example-click-events.html
- [x] Event delegation on the click event
- [x] Add selection events (use selected) and fix selection styling https://main-enterprise.demo.design.infor.com/components/listview/example-events.html
