### ISSUE TITLE
IdsLocale: Remaining Features/Issues

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#663]
**Description**
Lists the Remaining Bugs/Features for a 100% Component

**Major**

- [x] Dont use container for locale
- [x] Number Inputs (value/mask) https://github.com/infor-design/enterprise-wc/issues/564
- [x] Date Inputs (value/mask) https://github.com/infor-design/enterprise-wc/issues/564
- [x] Support Rounding/Not Rounding https://github.com/infor-design/enterprise-wc/issues/347
- [x] Fix https://github.com/infor-design/enterprise/issues/6123
- [x] Fix https://github.com/infor-design/enterprise/issues/6122
- [x] Fix https://github.com/infor-design/enterprise/issues/5255
- [x] Find a way to have it on every component again without duplication (lazy loading web pack comps) #1107
- [x] Change fonts for some locales via tokens
- [x] Add Locale to Stats (mixin?)
- [x] Update https://github.com/infor-design/enterprise/issues/7787 and submit translations
- [x] Fix https://github.com/infor-design/enterprise/issues/5119
- [x] Show changing locale in a side by side example and docs

**Additional context**
Original Issue #121

**Comment by ericangeles** [comment]
@tmcconechy for the Latvian https://github.com/infor-design/enterprise/pull/6410
