### ISSUE TITLE
IdsTabs: Remaining Features/Issues

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#683]
**Original Issue:** #120
**Previous refactoring work:** #411  / #427

**Major**

- [x] #729
- [x] Add overflow detection feature (may need design review?)
- [x] Dismissible Tabs
- [x] `ids-tab-divider`: Improve accessibility + add aXe tests

**Minor**

- [x] Sortable Behavior ([Example](https://main-enterprise.demo.design.infor.com/components/tabs-module/example-sortable.html))
- [ ] test: for keyboard events
- [ ] test: figure out how to get coveralls + Jest to detect certain parts of code
- [ ] test: figure out why ids-tab.selected = false doesn't trigger in Jest
- [x] test: resolve aXe color contrast issues (disabled state, similar to other components)
- [ ] Review current solution for potential optimization (remove extraneous elements and looping)
