### ISSUE TITLE
Loading Indicator: Remaining Features

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#684]
**Describe the bug**

Make sure any and all changes are reflected in the new web component lib.
https://www.figma.com/file/PwwLkUtTxpxLzRJzm5kACM/?node-id=810%3A0

**Fixes**

- [ ] Add an example with the new circle loading indicator on a card
- [ ] Add an example with the new circle loading indicator on a page
- [x] Add an example with on buttons
- [x] Add an example on fields (input and trigger)
- [ ] Add the page loading example on top
- [ ] Add the refresh content action animation
- [ ] Add a visible property to hide and show it
- [x] RTL Not working
- [ ] Dark mode and contrast mode need work

**Additional context**
https://jira.infor.com/browse/UXD-2653

**Comment by ashachodavarapu** [comment]
Hi @tmcconechy ,is this ticket completed? But 3 of 9 tasks shows but the status is closed
Thanks

**Comment by tmcconechy** [comment]
@ashachodavarapu I decided not to add those. Is there something you were hoping for in this list?
