### ISSUE TITLE
IdsLookup: Remaining Features/Issues

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#686]
**Description**
Lists the Remaining Bugs/Features for a 100% Component

**Major**

- [ ] Keyboard - able to select a datagrid row with the keyboard (space ect) like the old version
- [ ] Input sizes example
- [x] Add `beforeclose`, close, after opened events and `vetoable` callback for beforeOpen
- [x] Example with Paging - both client and server side
- [x] Example with Filtering and Frozen Cols
- [X] Add `beforeopen`, opened, after opened events and `vetoable` callback for beforeOpen
- [x] Clearable X like https://main-enterprise.demo.design.infor.com/components/lookup/example-clearable.html

**Covered on other tasks**
- [x] Add beforeopen, opened, after opened events and vetoable callback for beforeOpen (ed on modal) #708
- [x] Add beforeclose, close, after opened events and vetoable callback for beforeOpen (ed on modal) #708

**Minor**

- [ ] Localize the No Results message
- [ ] Fix https://github.com/infor-design/enterprise-wc/issues/577
- [ ] Fix https://github.com/infor-design/enterprise/issues/5886
- [ ] Fix https://github.com/infor-design/enterprise/issues/4319
- [ ] Standalone css example / example with no modal and a click event
- [x] Clearable X like https://main-enterprise.demo.design.infor.com/components/lookup/example-clearable.html
- [x] Search field above grid
- [x] Modal button in dark mode

**Additional context**
Original Issue #308
