### ISSUE TITLE
IdsMenu/IdsMenuButton: Remaining Features/Issues

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#689]
**Description**
Lists the Remaining Bugs/Features for a 100% Component

**Major**

- [x] Ensure current aria labels work properly to describe groups (Voiceover doesn't currently read out group headers)
- [x] Disabled state (entire menu)
- [x] Add option that replaces text with the selected item https://main-enterprise.demo.design.infor.com/components/button/example-menubutton-replace-text.html

**Minor**

- [x] Get aXe tests passing
- [x] Css only example

**Additional context**
Original Issue #170

**Comment by EdwardCoyle** [comment]
Note for whoever picks this one up to also review IdsPopupMenu, which has all the same issues outstanding but will inherit the fixes from this one.
