### ISSUE TITLE
IdsSplitter: Remaining Features/Issues

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#694]
**Original Issue:** #143

**Major:**
- [ ] Does not work on a touch device (ipad/iphone in chrome dev tools) ([#691](https://github.com/infor-design/enterprise-wc/issues/691))
- [ ] Save positions to local storage ([#692](https://github.com/infor-design/enterprise-wc/issues/692))
- [ ] Add API methods for sizing/expanding/collapsing split panes ([#693](https://github.com/infor-design/enterprise-wc/issues/693))
- [ ] Add trigger button to toggle collapse/expand to split-bar
- [ ] Fix aria-controls error for split-bar
