### ISSUE TITLE
IdsSpinbox: Remaining Features/Issues

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#696]
**Original Issue:** #139

**Major:**

- [ ] Allow valid user input on "step"-constrained fields ([#695](https://github.com/infor-design/enterprise-wc/issues/695))
- [ ] Sizes (full, large, compact ect)

**Minor:**

- [ ] Make Spinbox remember last "good" value when pressing increment or decrement if a user has cleared it

**Comment by tmcconechy** [comment]
Descoping this in favor of specific issues
