### ISSUE TITLE
IdsSearchField: Remaining Features/Issues

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#700]
**Original Issue:** #314

**Major:**

- [ ] Add responsive behavior (opt-in via boolean attribute) for existence within Toolbars or other containers [(example)](https://main-enterprise.demo.design.infor.com/components/toolbarsearchfield/example-flex-toolbar-align-with-searchfield.html) - includes a focusable "collapse" button for accessibility. (Skip go button just the mobile look)
- [ ] Check dark/contrast theme colors for `app-menu` color variant
- [x] Check Figma for New or conflicting Designs https://www.figma.com/file/yaJ8mJrqRRej8oTsd6iT8P/IDS-(SoHo)-Component-Library-v4.5?node-id=760%3A771&t=Hn2ppFMeWdP3xPLC-0 

**Minor:**

- [x] Check dark/contrast theme colors for `alternate` variant
- [x] Add categories functionality (named slot? + dropdown or menu button + callbacks/events for menu selection) [("short categories" example)](https://main-enterprise.demo.design.infor.com/components/searchfield/example-categories-short.html) [("full categories" example)](https://main-enterprise.demo.design.infor.com/components/searchfield/example-categories-full.html)
- [x] Side-by-side Example
- [ ] Standalone CSS Example

**Comment by tmcconechy** [comment]
@clayinfor can you take a look at the points from QA on an addition PR when you have a moment?

**Comment by clayinfor** [comment]
ok @tmcconechy , thanks for feedback @jbrcna 👍

**Comment by jbrcna** [comment]
you're welcome 🙂
