### ISSUE TITLE
IdsRating: Remaining Features/Issues

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#703]
**Original Issue:** #119 

**Major**

- [ ] Update number of stars (and current value if applicable) when `stars` attribute changes
- [ ] Themes: Implement color changes for Themes

**Minor**

- [ ] Private Methods and Classes: Make anything private that should be with # on the name
- [ ] Remove observed attributes that are covered by mixins (mode/version/etc)
- [ ] Standalone CSS Example
- [ ] Sandbox example page (customize the number of stars via an input/selection? / enable/disable readonly)
