### ISSUE TITLE
IdsPopup: Remaining Features/Issues

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#707]
**Original Issue:** #28 | #135 

**Major**

- [x] Fix bug related to `is-flipped` setting ([#339](https://github.com/infor-design/enterprise-wc/issues/339))
- [ ] Add test cases for multiple Popup types tied to the same trigger element ([#472](https://github.com/infor-design/enterprise-wc/issues/472))

**Minor**

- [ ] Rename "containment" to "constraint"
