### ISSUE TITLE
IdsScrollView: Remaining Features/Issues

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#709]
**Original Issue** #199 

**Major**

- [ ] Add a "multiple" view (display multiple/all pageable items when the container width allows)
- [ ] Go to full size pager if many items
- [ ] Themes

**Minor**

- [x] Ripple effect (see designs)
- [x] Side-by-side Example
- [x] Standalone CSS Example
