### ISSUE TITLE
IdsMessage: Remaining Features/Issues

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#712]
**Original Issue** #117 

**Major**

- [ ] Add Docs/guidance and make sure examples follow: https://github.com/infor-design/enterprise/issues/5821
- [ ] Add example for huge text like https://main-enterprise.demo.design.infor.com/components/message/example-index.html (to the types page)
- [ ] Add example for confirmation like https://main-enterprise.demo.design.infor.com/components/message/example-index.html (to the types page)
- [ ] Add tests or example to show that the modal events will fire on the message as well
- [ ] In dark mode the icon is hard to see as are the modal buttons (especially hover state)
- [ ] When opening the overlay "blinks"

**Minor**

- [ ] Side By Side Example
- [ ] Ability to set the opacity of the overlay https://main-enterprise.demo.design.infor.com/components/message/test-overlay-opacity.html (maybe modal)
