### ISSUE TITLE
IdsMonthView: Remaining Features/Issues

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#713]
**Original Issue** #444 

**Major**

- [ ] Keyboard still not 100% working like https://github.com/infor-design/enterprise/blob/main/src/components/monthview/readme.md#keyboard-shortcuts - needs a focus state border and when moving dates the color stays on the previous date
- [ ] Add disables dates (non selectable) - see old API which can be improved - example https://main-enterprise.demo.design.infor.com/components/monthview/test-disable-weekends.html (style is too dark)
- [ ] Expose the example for https://main-enterprise.demo.design.infor.com/components/monthview/test-inpage-variations.html (i know it works but not seeing the example)
- [ ] Add events (or callbacks) `keydown` and `changeview` and `beforemonthrendered` and `monthrendered` and `aftermonthrendered` and docs for these
- [ ] Add styling for today in addition to selected see https://github.com/infor-design/enterprise/issues/5065 and design issues
- [ ] Check thoroughly through https://github.com/infor-design/enterprise/issues/5763 for any design changes (may need to be discussed)
- [x] Dates in RTL mode look scrambled like `Ø§Ù„Ø®Ù…ÙŠØ³` on https://main.wc.design.infor.com/ids-month-view/

**Minor**

- [ ] May need example https://main-enterprise.demo.design.infor.com/components/monthview/example-inpage.html but skip for now
- [ ] Add example like https://main-enterprise.demo.design.infor.com/components/monthview/test-legend-loaded.html with an event for when the legend is loaded allowing you to use ajax on it (see dropdown beforeOpen)
- [ ] Skip https://github.com/infor-design/enterprise/issues/5881 until further notice
- [ ] Side by side example
