### ISSUE TITLE
IdsNotificationBanner: Remaining Features/Issues

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#715]
**Original Issue** #229 

**Major**

- [x] Address design changes on https://github.com/infor-design/enterprise-wc/issues/714 (some may need discussion)

**Minor**

- [x] Standalone css example
- [x] Side by side example
- [x] RTL View has link too close
- [x] Some sort of keyboard handling (maybe just the you can use the tab to navigate)

**Comment by tmcconechy** [comment]
is this one all finished @jmacaluso711 it didnt close on the PR merge?
