### ISSUE TITLE
IdsPager: Remaining Features/Issues

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#717]
**Original Issue** #148 

**Major**

- [x] Right-hand menu component for selecting page sizes and check the aria on it https://github.com/infor-design/enterprise/issues/6337
- [x] Setting for tooltips on the ids-pager-button elements
- [x] Events for all these https://github.com/infor-design/enterprise/blob/main/src/components/pager/pager.js#L1350
- [ ] RTL mode is not working (wrong directions)
- [x] Type in pager input and go to next it disappears

**Minor**

- [x] Standalone css version
- [x] Example on ListView (ok if done under listview TODO's) (Deepak addressing on #661
