### ISSUE TITLE
IdsDataGrid: M3 Feature Set

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#737]
**Describe the bug**
Trying to make sure the M3 features are available with virtual scrolling in the new grid. Need to test these a bit but some are done

**Examples and Related Tasks**
- [x] Improve modularity  https://github.com/infor-design/enterprise-wc/issues/962
- [x] In virtual scroll with selection the selectedRows data is returning the wrong indexes (need to investigate)
- [x] Show styling a custom formatter
- [x] Show a click callback in a custom formatter with a <a> in it
- [x] #989
- [x] #990
- [x] Virtual scroll down arrow key (keyboard) https://github.com/infor-design/enterprise-wc/issues/929
- [x] Better recycling https://github.com/infor-design/enterprise-wc/issues/972 in virtual scrolling
- [x] #996
- [x] https://github.com/infor-design/enterprise-wc/issues/667 for context menus
- [x] https://github.com/infor-design/enterprise-wc/issues/1005
- [x] https://github.com/infor-design/enterprise-wc/issues/1006
- [x] https://github.com/infor-design/enterprise-wc/issues/1008
- [x] https://github.com/infor-design/enterprise-wc/issues/1018
- [x] #1019

**Features**

- [x] disableClientFilter setting https://github.com/infor-design/enterprise-wc/issues/932
- [x] filterable https://github.com/infor-design/enterprise-wc/issues/932
- [x] tree grid 
- [x] expandable row
- [x] custom formatter example
- [x] column reorder
- [x] selection (multiple)
- [x] stretchColumn
- [x] #896
- [x] #991
  - [x] show dirty cell
  - [x] track dirty row and column in edit mode
  - [x] readonly and disabled cells and rows
- [x] #992
- [x] textOverflow
- [x] sortable
- [x] xss https://github.com/infor-design/enterprise-wc/issues/899
- [x] headerAlign
- [x] checkbox formatter
- [x] context menu on header and rows https://github.com/infor-design/enterprise-wc/issues/963
- [ ] scrollRowIntoView function like old version https://github.com/infor-design/enterprise-wc/issues/929
- [x] #993

**Events**
- [x] filtered https://github.com/infor-design/enterprise-wc/issues/932
- [x] #994
- [x]  selected (now selectionChanged or rowSelection/rowDeselection)
- [x] onBeforeSelect / selected - for a dropdown editor #991
- [x] beforeentereditmode / entereditmode / exiteditmode #991
- [x] cellchanged #991

**Filter Types**
https://github.com/infor-design/enterprise-wc/issues/932
- [x]  FilterTypes.Date
- [x]  FilterTypes.Integer
- [x]  FilterTypes.Decimal
- [x]  FilterTypes.Dropdown
- [x]  FilterTypes.Text
- [x]  FilterTypes.Custom

**Formatters**
- [x]  Soho.Formatters.Text (now formatters.text)
- [ ]  Soho.Formatters.Dropdown #991
- [x]  Soho.Formatters.Date (now formatters.date)
- [x]  Soho.Formatters.Checkbox (now formatters.checkbox)
- [x]  Soho.Formatters.Input (now formatters.text but needed editor)
- [x]  Soho.Formatters.Hyperlink  (now formatters.hyperlink)
- [x]  Soho.Formatters.Tree
- [x]  Soho.Formatters.Expander: used for M3 Experience Designer (previously App Designer)
- [x]  Soho.Formatters.Readonly - deprecated can now be set on the column and used with other formatters

**Comment by tmcconechy** [comment]
All items on this issue are completed. See https://github.com/infor-design/enterprise-wc/issues?q=is%3Aissue+is%3Aopen+label%3A%22team%3A+m3%22 for future issues
