### ISSUE TITLE
IdsMultiselect: Remaining Features/Issues

### ISSUE THREAD

**Issue by Jah25** [infor-design/enterprise-wc#741]
## Major

- [x] Keyboard functionality that works with grouped selection options
- [ ] respecting initial sorting of option groups

## Minor

- [x] visual bug with selection options checkbox color matches back ground color

**Comment by tmcconechy** [comment]
Duplicate issue found, closing
