### ISSUE TITLE
Chore: Expand Memory Leak tests

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#761]
**Describe the bug**
Improve these tests so it can be extended and used on more components. https://github.com/infor-design/enterprise-wc/pull/756/files#diff-50223d3fa887eb0d6f01fbdda9cfdc9e64cb4599fe94abb3bab76ad956a6989aR20

**TODO**

- [ ] See why it sometimes fails
- [ ] Print out what the difference is in the console for debugging
- [ ] Try it on more components
- [ ] Unskip the places its skipped

**Expected behavior**
Nice clean test for memory leaks with better debugging if it goes wrong

**Comment by tmcconechy** [comment]
This was surpassed by #668  and #878
