### ISSUE TITLE
IdsMultiselect: Additional Features/Fixes

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#807]
**Describe the bug**
The multiselect needs a little love so it works closer to https://main-enterprise.demo.design.infor.com/components/multiselect/example-index.html

**Tasks**
At least the following (may sync more tasks:

- [x] Keyboard Support
- [x] tags example is opening in wrong position
- [x] styling is off compared to old version (including groups)
- [x] doesn't stay open when selecting
- [x] Recheck #742 #363 
- [x] TODOs.md
