### ISSUE TITLE
IdsBundleSize: Improve Bundle Size / Performance

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#813]
**Describe the bug**
The bundle size is a bit large as code is not 100% shared correctly (known issue)

**Tasks**

- [ ]  Compare to other Enterprise grade libraries from IBM/Salesforce/Vaadin (in terms of bundle size)
- [ ] Define what is bundle size (npm package / download) i.e. measure
- [x] #814
- [x] Code Splitting
- [x] Analyzing code results from lighthouse (and improve)
- [ ] Micro Front Ends (maybe future)
- [ ] What can we do to be more "mobile first" (loose the encapsulation)
- [ ] Make a tailwind css type thing and docs on the current tokens

**Additional context**
TBD
