### ISSUE TITLE
IdsDatagrid: Ability to add custom icons

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#990]
**Task**

The m3 team has some of their own custom icons. And they use them in the data-grid. The example https://main.wc.design.infor.com/ids-data-grid/columns-formatters.html shows a button with an icon in.

- [ ] Device a way to extend the ids-icon lib with custom icons. Its ok if we prescribe what they need to do too add it
- [ ] For testing can take an existing icon and make a small "custom modification" to it to use as any example. Perhaps this is an `addIcon` method that appends to the internal svg data array so it can be used. Make an example
- [ ] Make sure this works in the datagrid example (add a new column for "custom icon"

**Comment by tmcconechy** [comment]
[h5-icons.zip](https://github.com/infor-design/enterprise-wc/files/10033204/h5-icons.zip)

Attached some example icons - we can use the data for the custom example for one.
